# -*- coding: utf-8 -*-
"""card.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2FFaPwWsc7sF2MxQZFvxOTd6DyHxoAK
"""

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/creditcardcsvpresent.csv')
df

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

df

df.isnull().sum()

null_var = df.isnull().sum()/df.shape[0]*100 
null_var

drop_columns = null_var[null_var > 20].keys()
drop_columns

df2_drop_col = df.drop(columns = drop_columns)
df2_drop_col

sns.heatmap(df2_drop_col.isnull())

#we need to find out only numerical value as all the null data has been cleared 
num_var = df2_drop_col.select_dtypes(include = ['int64','float64']).columns
num_var

type('Transaction date')

#visualize each feature 
for i ,var in enumerate(num_var):
  sns.displot(df2_drop_col[var],bins = 20)

